[tool.briefcase]
project_name = "Mathgame"
bundle = "com.example"
version = "0.0.1"
url = "https://github.com/pauldjackson70/Mathgame"
license = "BSD license"
author = 'Paul D Jackson'
author_email = "paul.d.jackson70@gmail.com"

[tool.briefcase.app.mathgame]
formal_name = "Mathgame"
description = "An application built with Beeware's Toga to test basic math"
icon = "src/mathgame/resources/mathgame"
sources = ['src/mathgame']
requires = []


[tool.briefcase.app.mathgame.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.mathgame.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.mathgame.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.mathgame.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.mathgame.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
